// Generated by ReScript, PLEASE EDIT WITH CARE


var General = {};

var Framework = {};

var Network = {};

var System = {};

export {
  General ,
  Framework ,
  Network ,
  System ,
}
/* No side effect */
